config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/quote' => 'quotes#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote
	require 'csv'

	def self.fetch_random
		csv = CSV.open("#{Rails.root}/lib/quotes.csv", headers: true)
		lines = csv.readlines
		lines[rand(lines.size)]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
# require 'csv'
class QuotesController < ApplicationController

	def show
		# csv = CSV.open("#{Rails.root}/lib/quotes.csv", headers: true)
		# lines = csv.readlines
		# @random_quote = lines[rand(lines.size)]

		@random_quote = Quote.fetch_random

 		respond_to do |format|
      format.html { @random_quote }
      format.json { render json: @random_quote }
      format.xml do 
      	render xml: { quote: @random_quote[0], author: @random_quote[1] }.to_xml 
      end
    end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/show.html.erb
<div style="text-align: center;">
	<h2>Today's quote</h2>

	<p>
		<h3><%= @random_quote[0] %></h3>
	</p>
	<p>
  	- Author <i><%= @random_quote[1] %></i>
  </p>
 </div>

app/views/welcome/index.html.erb
<h2>Hello world</h2>
<p>The time is now: <%= Time.now %></p>

<h3>Get a random quote by clicking a format below:</h3>

<ol>
	<li><%= link_to 'HTML', quote_path %></li>
	<li><%= link_to 'JSON', quote_path(format: 'json') %></li>
	<li><%= link_to 'XML', quote_path(format: 'xml') %></li>
</ol>